# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BSD_UI\Client_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_pic = QtWidgets.QLabel(Dialog)
        self.label_pic.setMinimumSize(QtCore.QSize(130, 130))
        self.label_pic.setMaximumSize(QtCore.QSize(130, 130))
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.horizontalLayout.addWidget(self.label_pic)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_nom = QtWidgets.QLabel(Dialog)
        self.label_nom.setStyleSheet("color: black;\n"
"border-color:gray;\n"
"border-width:1px;\n"
"border-style:solid;\n"
"border-radius:3px;\n"
"padding:1.5px;\n"
"margin: 10px, 10px;\n"
"margin-left: 10px;\n"
"margin-right: 10px;")
        self.label_nom.setObjectName("label_nom")
        self.verticalLayout_2.addWidget(self.label_nom)
        self.label_prenom = QtWidgets.QLabel(Dialog)
        self.label_prenom.setStyleSheet("color: black;\n"
"border-color:gray;\n"
"border-width:1px;\n"
"border-style:solid;\n"
"border-radius:3px;\n"
"padding:1.5px;\n"
"margin: 10px, 10px;\n"
"margin-left: 10px;\n"
"margin-right: 10px;")
        self.label_prenom.setObjectName("label_prenom")
        self.verticalLayout_2.addWidget(self.label_prenom)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("color: black;\n"
"border-color:gray;\n"
"border-width:1px;\n"
"border-style:solid;\n"
"border-radius:3px;\n"
"padding:1.5px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView_algo = QtWidgets.QListView(Dialog)
        self.listView_algo.setObjectName("listView_algo")
        self.verticalLayout.addWidget(self.listView_algo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Client Details"))
        self.label_nom.setText(_translate("Dialog", "Nom:"))
        self.label_prenom.setText(_translate("Dialog", "Prenom:"))
        self.label.setText(_translate("Dialog", "Algorithms"))
        self.pushButton.setText(_translate("Dialog", "OK"))
