# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BSD_UI\communicationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainComm(object):
    def setupUi(self, MainComm):
        MainComm.setObjectName("MainComm")
        MainComm.resize(700, 500)
        MainComm.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.centralwidget = QtWidgets.QWidget(MainComm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_back = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.button_back.setMinimumSize(QtCore.QSize(0, 30))
        self.button_back.setStyleSheet("background-color: rgb(79, 164, 244);\n"
"border-top-color: rgb(125, 128, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Arial\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 227, 246);\n"
"border-radius: 15px;\n"
"color: rgb(79, 164, 244);\n"
"font: 75 14pt \"Arial\";\n"
"border:2px solid rgb(79, 164, 244);\n"
"border-radius:10px;")
        self.button_back.setObjectName("button_back")
        self.horizontalLayout_2.addWidget(self.button_back)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(340, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.button_send = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.button_send.setMinimumSize(QtCore.QSize(0, 30))
        self.button_send.setStyleSheet("background-color: rgb(79, 164, 244);\n"
"border-top-color: rgb(125, 128, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Arial\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 227, 246);\n"
"border-radius: 15px;\n"
"color: rgb(79, 164, 244);\n"
"font: 75 14pt \"Arial\";\n"
"border:2px solid rgb(79, 164, 244);\n"
"border-radius:10px;")
        self.button_send.setObjectName("button_send")
        self.horizontalLayout_2.addWidget(self.button_send)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 330, 429))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_client = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_client.setFont(font)
        self.label_client.setStyleSheet("color:black;")
        self.label_client.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_client.setObjectName("label_client")
        self.horizontalLayout_3.addWidget(self.label_client)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_server = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_server.setFont(font)
        self.label_server.setStyleSheet("color:black;")
        self.label_server.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_server.setObjectName("label_server")
        self.horizontalLayout_4.addWidget(self.label_server)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainComm.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainComm)
        QtCore.QMetaObject.connectSlotsByName(MainComm)

    def retranslateUi(self, MainComm):
        _translate = QtCore.QCoreApplication.translate
        MainComm.setWindowTitle(_translate("MainComm", "Communication Window"))
        self.button_back.setText(_translate("MainComm", "Back"))
        self.button_send.setText(_translate("MainComm", "Send"))
        self.button_send.setShortcut(_translate("MainComm", "Return"))
        self.label_client.setText(_translate("MainComm", "Client:"))
        self.label_server.setText(_translate("MainComm", "Server:"))
