# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BSD_UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(241, 248, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout.setSpacing(34)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listClients = QtWidgets.QListWidget(self.centralwidget)
        self.listClients.setMaximumSize(QtCore.QSize(669, 360))
        self.listClients.setStyleSheet("#listClients {background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Arial\";\n"
"border-radius:5px;\n"
"border:2px solid rgb(79, 164, 244);\n"
"border-radius:10px;}")
        self.listClients.setObjectName("listClients")
        self.verticalLayout.addWidget(self.listClients)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 54))
        self.horizontalWidget.setMaximumSize(QtCore.QSize(16777215, 54))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout.setSpacing(160)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_scan = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_scan.setMinimumSize(QtCore.QSize(0, 45))
        self.button_scan.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.button_scan.setFont(font)
        self.button_scan.setStyleSheet("background-color: rgb(79, 164, 244);\n"
"border-top-color: rgb(125, 128, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Arial\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 227, 246);\n"
"border-radius: 15px;\n"
"color: rgb(79, 164, 244);\n"
"font: 75 14pt \"Arial\";\n"
"border:2px solid rgb(79, 164, 244);\n"
"border-radius:10px;")
        self.button_scan.setObjectName("button_scan")
        self.horizontalLayout.addWidget(self.button_scan)
        self.button_broadcast = QtWidgets.QPushButton(self.horizontalWidget)
        self.button_broadcast.setMinimumSize(QtCore.QSize(0, 45))
        self.button_broadcast.setMaximumSize(QtCore.QSize(145, 16777215))
        self.button_broadcast.setStyleSheet("background-color: rgb(79, 164, 244);\n"
"border-top-color: rgb(125, 128, 199);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Arial\";}\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 227, 246);\n"
"border-radius: 15px;\n"
"color: rgb(79, 164, 244);\n"
"font: 75 14pt \"Arial\";\n"
"border:2px solid rgb(79, 164, 244);\n"
"border-radius:10px;")
        self.button_broadcast.setObjectName("button_broadcast")
        self.horizontalLayout.addWidget(self.button_broadcast)
        self.verticalLayout.addWidget(self.horizontalWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server"))
        self.button_scan.setText(_translate("MainWindow", "Scan"))
        self.button_broadcast.setText(_translate("MainWindow", "BroadCast"))
